# Generated by Django 3.2.13 on 2022-10-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='txtfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='Files')),
            ],
            options={
                'db_table': 'textfile',
            },
        ),
    ]
